export const ALL_CAR_COLORS = 'All car colors';
export const ALL_MANUFACTURERS = 'All manufacturers';
export const PURCHASE= 'Purchase';
export const MY_ORDERS = 'My Orders';
export const SELL = 'Sell';
export const MAX_PAGES = '6'
export const VIEW_DETAILS = 'View details';
export const AVAILABLE_CARS = 'Available Cars';
export const FILTER = 'Filter';
export const MANUFACTURER = 'Manufacturer';
export const COLOR = 'Color';
export const DELETE = 'Delete';
export const FAV_LIST = 'Fav List';
export const NO_DETAILS = 'No details found for this car.';
export const CAR_LIKE_TEXT = 'If you like this car, click the button and save it in your collection of favourite items.'
export const CAR_STOCK_DETAIL = 'This car is currently available and can be delivered as soon as tomorrow morning. Please be aware that delivery times shown in this page are not definitive and may change due to bad weather conditions.'